"""Stable error codes. Clients branch on these, so values must not change once shipped."""

from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION_FAILED = "VALIDATION_FAILED"
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_PHONE = "INVALID_PHONE"
    INVALID_EXPERIENCE = "INVALID_EXPERIENCE"
    EMPTY_TECH_STACK = "EMPTY_TECH_STACK"
    TECH_STACK_TOO_LARGE = "TECH_STACK_TOO_LARGE"

    CANDIDATE_NOT_FOUND = "CANDIDATE_NOT_FOUND"
    INTERVIEW_NOT_FOUND = "INTERVIEW_NOT_FOUND"
    QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND"
    DUPLICATE_CANDIDATE = "DUPLICATE_CANDIDATE"

    INTERVIEW_ALREADY_FINALISED = "INTERVIEW_ALREADY_FINALISED"
    INTERVIEW_NOT_READY = "INTERVIEW_NOT_READY"

    LLM_UNAVAILABLE = "LLM_UNAVAILABLE"
    LLM_RATE_LIMITED = "LLM_RATE_LIMITED"
    QUESTION_GENERATION_FAILED = "QUESTION_GENERATION_FAILED"
    GRADING_FAILED = "GRADING_FAILED"

    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    FORBIDDEN = "FORBIDDEN"
    WEAK_PASSWORD = "WEAK_PASSWORD"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS"

    STORAGE_FAILED = "STORAGE_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
