"""add auth attempts

Revision ID: 669e407543da
Revises: 4352062f043a
Create Date: 2026-09-25 17:20:05.819898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '669e407543da'
down_revision: Union[str, Sequence[str], None] = '4352062f043a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_attempts_kind_key_created_at', 'auth_attempts', ['kind', 'key', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_attempts_kind_key_created_at', table_name='auth_attempts')
    op.drop_table('auth_attempts')
    # ### end Alembic commands ###
